spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password:

stripe:
  apiUrl: https://stripe.com/
  enabled: true
  timeout : 1000
  supported-currencies: USD,EUR,GBP

payment-gateway: paypal
